### ISSUE TITLE
fortiosconfig does not set the "no_log" flag

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/40ansible#24]
During an ansible play which references the fortiosconfig module in Ansible 2.7, I get a message indicating that the "no_log" option has not been set on a password field.

Could it be worth looking at using the native fortios modules in core Ansible to reduce your requirement to specify things like this: (e.g. https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/network/fortios/fortios.py#L45-L56) ?

**Comment by mamunozgonzalez** [comment]
Hi,
 thanks for you comment, actually it is a good point and we have already implemented the 'no_log' option in the new modules that are being submitted to Ansible. You can see them in: 

https://github.com/fortinet-solutions-cse/ansible_fgt_modules

I'll also submit a change to fortiosconfig to include "no_log":True for passwords.

Regarding module_utils/fortios.py, we are not using it due to we have our own fortiosapi.py library that we curate and keep alive. Unfortunately the other module does not seem to be maintained, we tried to contact the author but no luck so far.

**Comment by mamunozgonzalez** [comment]
I have added no_log option: https://github.com/fortinet-solutions-cse/40ansible/blob/master/library/fortiosconfig.py#L790
