### ISSUE TITLE
advanced auth parameters ?

### ISSUE THREAD

**Issue by nbonnand** [fortinet-solutions-cse/40ansible#44]
Hello,

Thanks for fortiosconfig module !

I am using fortigate_ssh.yml and I wonder if it is possible with fortiosconfig:
- to authenticate with ssh key instead of password ?
- to specify a ssh port number( for example 12345)  when it is not running on standard port 22 ?

Regards

Nicolas

**Comment by mamunozgonzalez** [comment]
Hi @nbonnand 
Thanks for your question. The SSH functionality under Ansible will be deprecated soon since it is not a good practice and was built just for some particular use cases that we couldn't cover some time ago. You can still use it, though.
Our recommendation is to use the official Ansible modules. Now in Ansible 2.9 you have a full set of modules to configure everything in FGT. You can check also our repo [https://github.com/fortinet-solutions-cse/ansible_fgt_modules](https://github.com/fortinet-solutions-cse/ansible_fgt_modules) that contains basically the same modules submitted to Ansible.

If you use ssh please keep in mind that:
It is not possible to use ssh key, just username and password.
It is not possible to customize the port from an Ansible playbook, but if you call fortiosapi library directly from python you can configure the port of your choice.

Hope that helps.

**Comment by thomnico** [comment]
Just a comment for clarity:
 using ssh key and port is indeed supported by Fortigate.

We will accept well tested pull request on 40ansible for this but won't develop or recommend to use ssh in an Ansible context.
